### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by felluksch** [kotarella1110/cordova-plugin-webpack#18]
Hi, thanks a lot for creating this plugin! I'm pretty new to Cordova and Javascript, so my problem might not even be related to your plugin but I'm going to try it here anyways.
When I'm running my Cordova app in the browser everything seems to work:
```
$ cordova run browser
Hash: 8e165a6fef6bb35bb020
Version: webpack 4.35.0
Time: 1818ms
Built at: 2019-06-30 2:56:23 PM
          Asset      Size  Chunks             Chunk Names
index.bundle.js  3.42 MiB    main  [emitted]  main
Entrypoint main = index.bundle.js
[./node_modules/leaflet-easybutton/src/easy-button.js] 9.89 KiB {main} [built]
[./node_modules/leaflet-freedraw/dist/leaflet-freedraw.web.js] 922 KiB {main} [built]
[./node_modules/leaflet/dist/leaflet-src.js] 397 KiB {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./www/index.js] 3.59 KiB {main} [built]
startPage = index.html
Static file server running @ http://localhost:8000/index.html
```
However, I get the following error in the console: "Uncaught ReferenceError: app is not defined at index.html:47". My index.html looks as follows: 
```
<script type="text/javascript" src="cordova.js"></script>
<script src="index.bundle.js"></script>
<script>
            app.init();
</script>
```
The method `app.init()` is defined in my index.js using `var app = { init: function() {…} }`. In the webpack.config.js file "entry" points to said index.js file. Do you have any idea why it doesn't work? Am I doing it wrong or misunderstanding something? Help much appreciated!

**Comment by kotarella1110** [comment]
@felluksch Thank you your feedback!
Your problem might not even be related to this plugin.
Use the global window object in your index.js with webpack.

```js
window.app = { init: function() {…} }
```

Thanks.

**Comment by felluksch** [comment]
Thank you! And sorry for bothering, I should have read up on webpack before using this plugin...

**Comment by felluksch** [comment]
Hello @kotarella1110 , sorry to bother you again. This is again unrelated to this actual plugin and more of a general webpack question. You were so kind to answer my previous question so maybe you will find another spare minute to help me. But please do not hesitate to just say you're busy and don't have time for that!
I've been trying for the last couple days to import libraries that aren't ES6 modules (i.e. that don't have export statements). The concerned libraries are [Leaflet.EasyButton](https://github.com/CliffCloud/Leaflet.EasyButton/issues/90) and [L.Pather](https://github.com/Wildhoney/L.Pather/issues/19). I tried the [shimming methods recommended in the webpack guide](https://webpack.js.org/guides/shimming/) but I couldn't get it working. Have you encountered similar problems by chance and know what to do? I thought I'd ask here before trying on Stackoverflow because you seem to be experienced with webpack-related issues. But again, as this has nothing to do with this plugin, don't feel pressured to answer! 
Thanks a lot (and if I can do anything for you, please let me know)!

Project folder: https://workupload.com/file/zkS3J6m4

**Comment by kotarella1110** [comment]
Hi @felluksch again! Help you in order to solve your problem.

`Leaflet.EasyButton` and` L.Pather` seem to overwrite Leaflet global object (`L`).

* https://github.com/CliffCloud/Leaflet.EasyButton/blob/v2.4.0/src/easy-button.js#L318
* https://github.com/Wildhoney/L.Pather/blob/v0.1.17/module/Pather.js#L40

You makes Leaflet available as a global variable (`L`) using `ProvidePlugin` and just import `leaflet-easybutton` and `leaflet-pather`.

`webpack.config.js`:

```diff
    plugins: [
      new webpack.ProvidePlugin({
        L: 'leaflet',
-       FreeDraw: 'leaflet-freedraw',
-       Easybutton: 'leaflet-easybutton',
-       Pather: 'leaflet-pather'
      })
    ],
```

`www/index.js`:

```diff
- import L from 'leaflet';
  import FreeDraw from 'leaflet-freedraw';
- import Pather from 'leaflet-pather';
+ import 'leaflet-pather';
  import 'leaflet-easybutton';
  import { writeToFile } from './js/export.js';

...

          // Pather
-         const pather = new Pather();
+         const pather = new L.Pather();
          map.addLayer(pather);
```

`L.Pather` requires [D3.js](https://github.com/d3/d3) v3.

https://github.com/Wildhoney/L.Pather/blob/v0.1.17/module/Pather.js#L132

You install D3.js v3 and makes D3.js available as a global variable (`d3`) using `ProvidePlugin`.

```shell
npm install d3@3
```

`webpack.config.js`:

```diff
    plugins: [
      new webpack.ProvidePlugin({
        L: 'leaflet',
+       d3: 'd3',
      })
    ],
```

**Comment by felluksch** [comment]
Thank you so much! This gave me quite a headache. Also thanks for the concise documentation so I can actually understand what's going on. 
Best wishes,
Felix

**Comment by kotarella1110** [comment]
That's good! I'm relieved to hear that.
