### ISSUE TITLE
I'm having issues using this, please help

### ISSUE THREAD

**Issue by Joseph-Ryu** [kotarella1110/cordova-plugin-webpack#2]
I'm new to Cordova and I would like to use webpack with my cordova project using your plugin but I'm having some issues.

Basically I followed your instructions but js files cannot recognize import/require.
I have basically hello world cordova starting app with your plugin. Could you look at it and tell me what I am doing wrong?

I attached my project.
I really appreciate your help.

[Archive.zip](https://github.com/kotarella1110/cordova-plugin-webpack/files/3134849/Archive.zip)

**Comment by kotarella1110** [comment]
@Joseph-Ryu Thanks for using this plugin.

Is the problem solved?
The problem is solved by fixing `www/index.html` as follows.

```html
-         <script type="text/javascript" src="js/index.js"></script>
+         <script type="text/javascript" src="dist/bundle.js"></script>
```

**Comment by Joseph-Ryu** [comment]
Yes I fixed it. Thank you for looking into it still!

**Comment by kotarella1110** [comment]
That's good!
I'm happy to hear that!
