### ISSUE TITLE
Cannot read property argv of undefined

### ISSUE THREAD

**Issue by SpellCraft** [kotarella1110/cordova-plugin-webpack#20]
Hello!
Absolutely loving this plugin.

I noticed a small issue when re-initializing an existing project
 * ```cordova prepare```
 * or when re-installing a platform ```cordova platform remove android && cordova platform add android```

after installing this plugin, it will continue to install all plugins, but end with ```Cannot read property 'argv' of undefined```

I'm unsure if this has any effect on the plugin overall as I've yet to experience any, but thought I'd give you a shout out about it.

**Comment by kotarella1110** [comment]
Hi @SpellCraft ! I'm glad to hear that.

Thanks for your feedback. 
I will address the issue as soon as possible!

**Comment by Aarbel** [comment]
same issue here with ios

**Comment by kotarella1110** [comment]
@SpellCraft @Aarbel In release [v0.4.6](https://www.npmjs.com/package/cordova-plugin-webpack/v/0.4.6), resolved this probrem!
