### ISSUE TITLE
Support for multiple webpack config

### ISSUE THREAD

**Issue by Aarbel** [kotarella1110/cordova-plugin-webpack#21]
![image](https://user-images.githubusercontent.com/25119847/63022637-a47b4700-bea3-11e9-8259-612be5ebf2a3.png)

Got this error when using multiple webpack configs : 
`configuration has an unknown property '1'` 

This is caused by webpack config of type array instead of object.

When will you support multi webpack configs ? Thanks ! 

My `webpack.config.xml`
```JS
var config = {
    devtool: 'inline-source-map',
    mode: 'development',
};

const cordovaAppConfig = Object.assign({}, config, {
    name: "cordovaAppConfig",
    entry: path.resolve(__dirname, 'src/index.js'),
    output: {
       path: path.resolve(__dirname, 'www/js'),
       filename: "index.bundle.js"
    },
});

const injectedJsConfig = Object.assign({}, config, {
    name: "injectedJsConfig",
    entry: path.resolve(__dirname, 'src/webview-injection.js'),
    output: {
       path: path.resolve(__dirname, 'www/js'),
       filename: "webview-injection.bundle.js"
    },
});

module.exports = [
    cordovaAppConfig, injectedJsConfig,       
];
```

**Comment by kotarella1110** [comment]
Hi @Aarbel !
This plugin does not support [exporting a Function and a Promise and multiple configurations](https://webpack.js.org/configuration/configuration-types/).
I plan to support these in the near future! But this will take a little more time.
Thanks.

**Comment by Aarbel** [comment]
thank you @kotarella1110

**Comment by kotarella1110** [comment]
@Aarbel In release [v1.0.0-alpha.1](https://github.com/kotarella1110/cordova-plugin-webpack/releases/tag/v1.0.0-alpha.1), supported exporting a Function and a Promise and multiple configurations!

Test it out:

```shell
$ cordova plugin add cordova-plugin-webpack@alpha
```
