### ISSUE TITLE
Better doc for ios and android, not browser

### ISSUE THREAD

**Issue by Aarbel** [kotarella1110/cordova-plugin-webpack#22]
The whole doc commands run cordova with default `browser` device.

Could be great to add examples about phone devices like ios.

Moreover this doc isn't very clear, we don't really understand what the `-w path/to/dir/webpack.config.babel.js -l` options are for.
![image](https://user-images.githubusercontent.com/25119847/63024513-a34c1900-bea7-11e9-8ae7-d4bfe07df382.png)

Thanks a lot !

**Comment by kotarella1110** [comment]
@Aarbel Thanks for your feedback!
I agree with you! But I am not very good at English.
If possible, Could you create PR?

**Comment by Aarbel** [comment]
Yes no problem, just explain me what `path/to/dir/webpack.config.babel.js -l` does ;)

**Comment by kotarella1110** [comment]
@Aarbel Thanks.
The `-w` option is an alias option for `--webpackConfig` option.
The `-l` option is an alias option for `--livereload` option.

**Comment by kotarella1110** [comment]
Close this because no response. Feel free to reopen the issue if it's needed.
