### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by kotarella1110** [kotarella1110/cordova-plugin-webpack#23]
Test it out:

```
$ npm install -D webpack@4 webpack-cli@3 webpack-dev-server@3
$ cordova plugin add cordova-plugin-webpack@alpha
```

# Removed webpack packages from deps

This plugin depends on the plugin's own webpack, but it will be modified to depend on the webpack you installed.
Therefore, removed webpack packages (`webpack`, `webpack-cli`, `webpack-dev-server`) from deps of `package.json` and add the webpack packages to peerDeps (https://github.com/kotarella1110/cordova-plugin-webpack/commit/2b86b413296e09b3fc820d1b2c7d827fc3686426).
You need to install the webpack packages yourself before installing this plugin.

```shell
$ npm install -D webpack@4 webpack-cli@3 webpack-dev-server@3
```

# Add a new `--webpack` option

This plugin has no way to map parameters sent to the CLI to a corresponding parameter in the webpack configuration file such as webpack-cli and webpack-dev-server.
Add a new `--webpack` option to make this possible.

`--webpack` option's parameters is passed to [webpack-cli options](https://webpack.js.org/api/cli/) or [webpack-dev-server options](https://webpack.js.org/configuration/dev-server/).

```
$ cordova build ios -- --webpack.mode=production
$ cordova build ios -- --webpack.env.prod
$ cordova run android -- --livereload --webpack.port=8888 --webpack.watch-content-base=false
```

**The `--webpackConfig` option will be removed in v1** by adding a new `--webpack` option.
Use `--webpack.config` option instead of `--webpackConfig` option.

```diff
- $ cordova build ios -- --webpackConfig example.config.js
+ $ cordova build ios -- --webpack.config example.config.js
```

# Support [various webpack configuration types](https://webpack.js.org/configuration/configuration-types)

This plugin only supports exporting a single configuration object.
Covers other needs besides exporting a single configuration object.

Related Issues:
* #21
* #19

**Comment by Kepro** [comment]
hey, do you have ETA? :) or how close are you?

**Comment by kotarella1110** [comment]
@Kepro Sorry :cry:
I couldn't this work recently, but I will start working again this week!
The bulk of this work is finished.
This work will be finished in December at the earliest.

**Comment by Kepro** [comment]
@kotarella1110 do you need any help or smth?

**Comment by kotarella1110** [comment]
I need the following help.

* Update README for v1.
* Support for some options such as [Stats Options](https://github.com/webpack/webpack-cli/blob/master/bin/cli.js) or [Watch Options](https://webpack.js.org/api/cli/#watch-options) defined in [`cli.js` of webpack-cli](https://github.com/webpack/webpack-cli/blob/master/bin/cli.js).
