### ISSUE TITLE
Adding support for Cordova Sqlite Storage

### ISSUE THREAD

**Issue by SpellCraft** [kotarella1110/cordova-plugin-webpack#24]
Hello!

I was wondering if it's possible to add support for the highly popular cordova sqlite storage plugin? I'm not really sure how it's working behind the scenes, but as far as I can tell, the plugin is not lodaded/injected into the project until you run the project manually on a device or emulated one.

```cordova prepare && cordova run android``` -- The plugin works as expected
```rimraf www/* && cordova prepare && cordova run -- -livereload``` -- The plugin fails to load.

Is this something you're able to do on your side?

**Comment by kotarella1110** [comment]
@SpellCraft Hey again!
LiveReload is impossible to support native plugins like cordova-sqlite-storage.
LiveReload only works with plugins that support browser platforms.

cordova-sqlite-storage currently supports browser platforms with some limitations!
If you want to run cordova-sqlite-storage with LiveReload, please see [here](https://github.com/xpbrew/cordova-sqlite-storage#browser-platform-usage-notes "Browser platform usage notes").

**Comment by SpellCraft** [comment]
Thanks for the input kotarella! With some tinkering, I think I actually managed to get it to work as.

Say you setup the database object like so;
```javascript
const database = () => {
  return new Promise((resolve, reject) => {
    document.addEventListener('deviceready', () => {
      const db = window.sqlitePlugin.openDatabase({
        name: 'my.db',
        location: 'default',
      });
      if (!db) {
        reject();
      } else {
        resolve(db);
      }
    });
  });
};
export default database;
```

When you then import the promisified DB delegate, this query ran successfully with LiveReload;
```javascript
database().then(db => {
  db.transaction(
    tx => {
      tx.executeSql('CREATE TABLE IF NOT EXISTS DemoTable (name, score)');
      tx.executeSql('INSERT INTO DemoTable VALUES (?,?)', ['Alice', 101]);
      tx.executeSql('INSERT INTO DemoTable VALUES (?,?)', ['Betty', 202]);
    },
    error => {
      console.log(`Transaction ERROR: ${error.message}`);
    },
    () => {
      console.log('Populated database OK');
      db.close();
    },
  );
});
```

**Comment by kotarella1110** [comment]
Did it work?

I think it should be as follows.

```js
const database = () => {
  return new Promise((resolve, reject) => {
    document.addEventListener('deviceready', () => {
      const db = window.sqlitePlugin ? window.sqlitePlugin.openDatabase({
          name: 'my.db',
          location: 'default',
        }) : window.openDatabase({
          name: 'my.db',
          location: 'default',
        });
      if (!db) {
        reject();
      } else {
        resolve(db);
      }
    });
  });
};
export default database;
```

**Comment by SpellCraft** [comment]
Yeah. It's working just fine both with the live-server and on the app itself. :)

**Comment by kotarella1110** [comment]
That's good!
If it is not a problem for you, close this!
