### ISSUE TITLE
How to specify a specific platform？

### ISSUE THREAD

**Issue by weishijun14** [kotarella1110/cordova-plugin-webpack#26]
In readme
```
cordova run -- --livereload
```
can work.

But like this: 
```
cordova run android --emulator --livereload
// or 
cordova run android --livereload
```
will fail to livereload. as follow pic:

![image](https://user-images.githubusercontent.com/20705423/69771991-a73b4700-11c9-11ea-8e09-4aed6eb1d88f.png)

**Comment by weishijun14** [comment]
By the way, is this normal ? when I check chrome remote devices: 
![image](https://user-images.githubusercontent.com/20705423/69774208-3fd4c580-11d0-11ea-874a-cfa529d02018.png)

**Comment by kotarella1110** [comment]
> READMEで
> 
> ```
> cordova run -- --livereload
> ```
> 
> 働ける。
> 
> しかし、このように：
> 
> ```
> cordova run android --emulator --livereload
> // or 
> cordova run android --livereload
> ```
> 
> ライブリロードに失敗します。写真に従ってください：
> 
> ![画像](https://user-images.githubusercontent.com/20705423/69771991-a73b4700-11c9-11ea-8e09-4aed6eb1d88f.png)

The CLI command you executed is wrong!
Execute CLI with `--`  before `--livereload`.

```
cordova run android --emulator -- --livereload
// or 
cordova run android -- --livereload
```

**Comment by kotarella1110** [comment]
> By the way, is this normal ? when I check chrome remote devices:
> ![image](https://user-images.githubusercontent.com/20705423/69774208-3fd4c580-11d0-11ea-874a-cfa529d02018.png)

You need to fix Content Security Policy in `www/index.html`

**Comment by weishijun14** [comment]
Thx a lot! bro, 
by the way, 
I use webpack resolve.alias like this: 


this is my file dictionary:
![image](https://user-images.githubusercontent.com/20705423/69778875-09537680-11e1-11ea-9386-89fa82b446b7.png)


this is webpack.common.js :
```
module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, "www"),
    filename: "index.bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.(j|t)sx?$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            cacheDirectory: true
          }
        }
      },
      {
        test: /\.css$/,
        use: [
          devMode ? "style-loader" : MiniCssExtractPlugin.loader,
          "css-loader"
        ]
      }
    ]
  },
  resolve: {
    // Add '.ts' and '.tsx' as resolvable extensions.
    extensions: [".ts", ".tsx", ".js", ".jsx", ".json"],
    alias: {
      "@": path.resolve(__dirname, "./src/app")
      // "react-dom": "@hot-loader/react-dom"
    }
  },

  plugins: [
    new CleanWebpackPlugin({
      // cleanOnceBeforeBuildPatterns: ["index.html"]
    }),
    new HtmlWebpackPlugin({
      title: "cwgx app",
      template: "src/index.ejs"
    }),
    new MiniCssExtractPlugin({
      filename: "[name].css",
      chunkFilename: "[id].css",
      ignoreOrder: false // Enable to remove warnings about conflicting order
    })
  ],
  devtool: "inline-source-map"
};

```

And I go `cordoca run -- --livereload`:  ( everytime I run this script, I do `cordova build`,

![image](https://user-images.githubusercontent.com/20705423/69778933-3ef85f80-11e1-11ea-9d65-039b82621ee7.png)

**Comment by kotarella1110** [comment]
Is your cordova project published on github?
If not, Is it possible to attach your cordova project?

**Comment by weishijun14** [comment]
> Is your cordova project published on github?
> If not, is it possible to attach your cordova project?

https://github.com/weishijun14/test-for-cordova  

Need `npm i` first.

Thanks agiain!

**Comment by kotarella1110** [comment]
You need to merge `webpack.common.js` into `webpack.config.js`.

`webpack.config.js`:

```diff
  const path = require("path");
+ const merge = require("webpack-merge");
+ const common = require("./webpack.common.js");

- module.exports = {
+ module.exports = merge(common, {
    mode: "development",
    entry: "./src/index.js",
    output: {
      path: path.resolve(__dirname, "www"),
      filename: "index.bundle.js"
    },
    devtool: "inline-source-map",
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader"
          }
        }
      ]
    }
- }
+ });
```

You will build successfully! 👍 

```shell
cordova run -- --livereload
```

**Comment by weishijun14** [comment]
It works~~
So only `webpack.config.js` after `--webpackConfig ` can work ?

**Comment by kotarella1110** [comment]
That's good! 👍 
If not use`--webpackConfig` option, this plugin import `webpack.config.js` or `webpackfile.js` in your project root directory by default.
