### ISSUE TITLE
ios-deploy complains about arguments

### ISSUE THREAD

**Issue by vitto32** [kotarella1110/cordova-plugin-webpack#29]
If i run
`cordova run ios --device -- --webpackConfig [path] --livereload`
ios-deploy complains:
`ios-deploy: unrecognized option '--livereload'`

**Comment by vitto32** [comment]
I've solved prepending another --
`cordova run ios --device -- --webpackConfig [path] -- --livereload`

**Comment by vitto32** [comment]
I closed the issue to soon, `-- --livereload` just ignores the command.

**Comment by kotarella1110** [comment]
@vitto32 Thanks for your feedback!
I think this can't fix with this plugin.
It seems that ios-deploy needs to be fixed.

**Comment by vitto32** [comment]
@kotarella1110 thank to you for the plugin!
Finally a I found a solution:
`-- --livereload --webpackConfig [config-path]`
passing the params in this order works!

**Comment by kotarella1110** [comment]
@vitto32 Thanks for finding the solution 👍

**Comment by peitschie** [comment]
Just as a random point of reference, it seems that the `run` command for `cordova ios` chops off only the first 2 arguments before calling `ios-deploy`. If more than two commands are passed, they accidentally leak out to `ios-deploy` and cause issues 😕 

https://github.com/apache/cordova-ios/blob/ea9751b1417e2f9baefdd9f9e7e36ad44ebed235/bin/templates/scripts/cordova/lib/run.js#L101

I was getting the above issue as well, and eventually fixed it by changing my command-line args into a single webpack config to avoid this limit.
