### ISSUE TITLE
Can't use webpack.config.babel.js?

### ISSUE THREAD

**Issue by JimmyMultani** [kotarella1110/cordova-plugin-webpack#6]
I was wondering if it would be possible to allow `webpack.config.babel.js` as the file name? Main reason being that I'm using ES6 syntax in the config file. I get this error when trying to run `cordova build`:

```
Cannot find module '/Users/jimmymultani/path/to/project/webpack.config.js'
```

Thanks.

**Comment by kotarella1110** [comment]
@JimmyMultani Thanks for using this plugin.

I just committed to add support for `webpack.config.babel.js`.
Please try the following.

Install the latest plugin for the develop branch.

```shell
$ cordova plugin add https://github.com/kotarella1110/cordova-plugin-webpack.git#develop
or
$ cordova plugin add git@github.com:kotarella1110/cordova-plugin-webpack.git#develop
```

Install Babel's packages if you have not installed it yet.

```shell
$ npm install @babel/core @babel/register --save-dev
```

All you have to do now is to specify the `.babelrc` config preset.

```shell
$ npm install --save-dev @babel/preset-env
```

`.babelrc`:

```
{
  "presets": [
    "@babel/preset-env"
  ]
}
```

Try to build.

```
$ cordova build
```

If it works well, I would like to publish to npm.

**Comment by kotarella1110** [comment]
Earlier, v0.3.0 was released.
Therefore, please install the plugin from npm.

```shell
$ cordova plugin add cordova-plugin-webpack
```

**Comment by JimmyMultani** [comment]
Hey @kotarella1110, I installed the latest plugin version you released and it works like a charm! Thank you for this fantastic plugin. :)
