### ISSUE TITLE
Is it possible to made HMR optional?

### ISSUE THREAD

**Issue by JimmyMultani** [kotarella1110/cordova-plugin-webpack#7]
Hey again,

I noticed that `hot: false` is being overwritten by the plugin, would it be possible to respect that parameter in case you just wanted to have the whole page reload instead of that particular module?

If you'd like, I can create a PR for this.

Thank you again.

**Comment by kotarella1110** [comment]
Hey again!

Yes, the plugin is overriding webpack `hot` option from `false` to `true`.
You may be right. You may want to reload the whole page instead of that particular module.

Please create a PR for this!!
I'm so happy that you are the first contributor to the plugin.

Thank you.
