### ISSUE TITLE
Custom webpack config not found

### ISSUE THREAD

**Issue by jvanderbiest** [kotarella1110/cordova-plugin-webpack#78]
Using the default `webpack.config.js` with a different entry `./src/index123.js`
```javascript
const path = require('path');
 
module.exports = {
  mode: 'development',
  entry: './src/index123.js',
  output: {
    path: path.resolve(__dirname, 'www'),
    filename: 'index.bundle.js',
  },
  devtool: 'inline-source-map',
};
```

then I created a copy of this config to `webpack.browser.config.js` and used entry `./src/index456.js`
running the command
`cordova run browser -- --livereload --webpack.browser.config.js`
still uses the `webpack.config.js` as it looks for `./src/index123.js` instead of `./src/index456.js`

Am I doing anything wrong? I'm using `cordova-plugin-webpack": "^1.0.2"`

**Comment by kotarella1110** [comment]
@jvanderbiest You should use `--webpack.<option>` option.

<img width="914" alt="スクリーンショット 2020-04-13 9 21 36" src="https://user-images.githubusercontent.com/12913947/79083270-3788bb80-7d68-11ea-9348-1dfcc7f57f18.png">

```
cordova run browser -- --livereload --webpack.config webpack.browser.config.js
```

**Comment by jvanderbiest** [comment]
@kotarella1110 thanks... and you were right because I missed some syntax there but that was because of my numerous attempts :-)

**Usage**
```bash
cordova run browser -- --livereload --webpack.config webpack.original.config.js
```
Uses the default config as the `webpack.original.config.js` has an invalid entry point and would fail the build. Also outputs an error: `The platform "webpack.original.config.js" does not appear to have been added to this project.`

**Screenshot**
![image](https://user-images.githubusercontent.com/3985995/79113787-fbfaeb00-7d81-11ea-857e-932785e11ad2.png)

I'm on a windows box, maybe that's related.

You can try it out with this repo
https://github.com/jvanderbiest/cordova-phaser-webpack-typescript/tree/19d44ef81fc38348c2a7531aa36446c82e513120

Just needs this in the game folder.
```bash
npm install
```

**Comment by kotarella1110** [comment]
@jvanderbiest Your entry file does not exist. Is this webpack configuration correct?

https://github.com/jvanderbiest/cordova-phaser-webpack-typescript/blob/19d44ef81fc38348c2a7531aa36446c82e513120/game/webpack.original.config.js#L5

I renamed your `webpack.config.js` to `webpack.original.config.js` and executed `cordova run browser -- --livereload --webpack.config webpack.original.config.js` and it worked correctly on macOS.

**Comment by kotarella1110** [comment]
@jvanderbiest Doesn't it work correctly with `=` (`--webpack.config=webpack.original.config.js`)?

```
cordova run browser -- --livereload --webpack.config=webpack.original.config.js
```

**Comment by jvanderbiest** [comment]
No it's the same thing. I also tried that before.

I guess then it is related to windows. If it works, then it's machine related so probably the way how windows handles it. I'll update the thread when I find out what's wrong.

Thanks for the help

**Comment by jvanderbiest** [comment]
I found the issue. My default Visual Studio Code editor uses PowerShell as terminal. Running it from there doesn't work. Running it in another bash shell like the one that comes with Git does work.

**Comment by kotarella1110** [comment]
@jvanderbiest Thanks for finding out the problem and the solution! 💯
