### ISSUE TITLE
plugin fails to work from different app path

### ISSUE THREAD

**Issue by romanlv** [kotarella1110/cordova-plugin-webpack#89]
I noticed that when my app is cloned by somebody else, whenever they try to run, it fails to create a bundle with a warning

```
> cordova run browser -- --livereload



Script file does't exist and will be skipped: <app path>/plugins/cordova-plugin-webpack/dist/webpackCompile.js

Script file does't exist and will be skipped: <app path>/plugins/cordova-plugin-webpack/dist/webpackServe.js

startPage = index.html

Static file server running @ http://localhost:8000/index.html

CTRL + C to shut down

304 /index.html

(node:7934) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

304 /css/index.css

304 /cordova.js

404 /index.bundle.js
```
---

It looks like the problem is caused by `_where` attribute in `plugins/cordova-plugin-webpack/package.json` that holds absolute path to the app folder when this plugin was installed 

As for now, the workaround is to 
```
cordova plugins rm cordova-plugin-webpack
cordova plugins add cordova-plugin-webpack
```
After pulling other people commits

**Comment by kotarella1110** [comment]
@romanlv Are you example repository to reproduce it?

**Comment by romanlv** [comment]
@kotarella1110 
Try this one https://github.com/romanlv/cordova-webpack-test 

I experimented with it a bit more, it looks like `npm i` does not install everything and `cordova plugins add cordova-plugin-webpack` is required to fully install it (unless it's a required step, I'm new to cordova development)

**Comment by kotarella1110** [comment]
@romanlv Thanks for providing the example 👍 
I will look into this.

**Comment by kotarella1110** [comment]
@romanlv Because the `platforms` and `plugins` depend on the individual, you should ignore them when managing your Cordova project with git.

```
# .gitignore
/platforms
/plugins
```


After cloning, perform the following steps.

```
npm i
cordova prepare
```

**Comment by romanlv** [comment]
@kotarella1110 Thanks for the help, the problem is solved
